# Generated by Django 4.2.26 on 2025-12-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_productimage_image_url_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='public'),
        ),
    ]
