# Generated by Django 4.2.26 on 2026-01-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/500', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
