# Generated by Django 4.2.26 on 2026-01-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_stock_count_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(blank=True, default='1', null=True),
        ),
    ]
