# Generated by Django 4.2.26 on 2026-09-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_shipping_product_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_locally',
            field=models.BooleanField(default=False, help_text='Available for local shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='ships_overseas',
            field=models.BooleanField(default=False, help_text='Available for international shipping'),
        ),
    ]
